import Foundation
import simd

// MARK: - Boundary Type

public enum BoundaryType: String, Codable, Sendable {
    /// Tap-to-place vertices, system auto-closes
    case polygon
    /// Continuous drag tracing, simplified on finger-lift
    case freeform
}

// MARK: - Wound Boundary

/// A wound boundary drawn by a nurse (primary path) or generated by AI (shadow path).
/// Contains both the 2D image-space points and their 3D projections onto the mesh.
public struct WoundBoundary: Codable, Sendable {

    /// Unique identifier for this boundary
    public let boundaryId: UUID

    /// How the boundary was created
    public let boundaryType: BoundaryType

    /// Who or what created this boundary
    public let source: BoundarySource

    /// 2D points in normalized image coordinates (0...1).
    /// Origin is top-left. Ordered as a closed polygon
    /// (last point connects back to first).
    public let points2D: [SIMD2<Float>]

    /// 3D world-space points projected onto the mesh surface.
    /// Same count and order as `points2D`.
    /// Populated after `BoundaryProjector` runs.
    public var projectedPoints3D: [SIMD3<Float>]?

    /// The nurse's initial tap point (normalized image coords).
    /// Used as SAM 2's point prompt on the backend.
    public let tapPoint: SIMD2<Float>?

    /// Timestamp when this boundary was drawn
    public let createdAt: Date

    public init(
        boundaryId: UUID = UUID(),
        boundaryType: BoundaryType,
        source: BoundarySource,
        points2D: [SIMD2<Float>],
        projectedPoints3D: [SIMD3<Float>]? = nil,
        tapPoint: SIMD2<Float>? = nil,
        createdAt: Date = Date()
    ) {
        self.boundaryId = boundaryId
        self.boundaryType = boundaryType
        self.source = source
        self.points2D = points2D
        self.projectedPoints3D = projectedPoints3D
        self.tapPoint = tapPoint
        self.createdAt = createdAt
    }
}

// MARK: - Boundary Source

public enum BoundarySource: String, Codable, Sendable {
    /// Drawn by a nurse on-device (primary path)
    case nurseDrawn = "nurse_drawn"
    /// Auto-generated on-device by Apple Vision foreground instance mask,
    /// then confirmed / edited by the nurse. The audit trail still shows
    /// this case so downstream agreement metrics can separate "purely
    /// manual" from "AI-assisted" boundaries.
    case autoVision = "auto_vision"
    /// Generated by SAM 2 on the backend (shadow path)
    case sam2 = "sam2"
    /// Corrected by a senior clinician during review
    case clinicianReview = "clinician_review"
}

// MARK: - SIMD2 Codable Conformance

extension SIMD2: @retroactive Codable where Scalar == Float {
    public init(from decoder: Decoder) throws {
        var container = try decoder.unkeyedContainer()
        let x = try container.decode(Float.self)
        let y = try container.decode(Float.self)
        self.init(x, y)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.unkeyedContainer()
        try container.encode(x)
        try container.encode(y)
    }
}

// MARK: - SIMD3 Codable Conformance

extension SIMD3: @retroactive Codable where Scalar == Float {
    public init(from decoder: Decoder) throws {
        var container = try decoder.unkeyedContainer()
        let x = try container.decode(Float.self)
        let y = try container.decode(Float.self)
        let z = try container.decode(Float.self)
        self.init(x, y, z)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.unkeyedContainer()
        try container.encode(x)
        try container.encode(y)
        try container.encode(z)
    }
}
